typedef struct inputs
{
    char name[100];
    int fill_input;
    char pos;
    int type_input;
    int size;
    char character_input;
    char fill_col;
    char outline_col;
    int height;
    char start_char;
    char end_char;
    char character_type;
    char color_choice;
    char start_num;
    char end_num;
    char character_selection;
    char drawChar;
    int colour;
    int x;
    int y;
    int color;
    char ch;
    char key;
    char main_type;
    char choice;

} inputs;

int get_terminal_width();
void print_horizontal_line(char symbol, int width);
int welcome();
int option();
int alphabet_screen();
int shapes_screen();
int numbers_screen();
int exit_screen();
void main_interface();
void main_shapes();
void main_numbers();
void main_triangle();
void main_sqaure();
void main_butterfly();
void main_daimond();
void main_oval();
void main_heart();
void main_hexagon();
void main_trapezium();
void main_parallelogram();
void main_pentagon();
void main_arrow();
void free_handrawing();
void clearCell(int x, int y);
void sha_pes();
void main_options();
void auto_saving();
void file_saving();
void view_file();
void file_edit();
void free_hand(char drawChar, int colour);